### ISSUE TITLE
awkward wording

### ISSUE THREAD

**Issue by bmcilhenny** [learn-co-curriculum/js-object-oriented-bind-call-apply-readme#10]
**Sometimes, bind is also to preserve this when invoked in a callback function. Let's see this.**

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @bmcilhenny.

We have updated the materials, rewrote this portion of the lesson and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
