### ISSUE TITLE
Last Example Code Doesn't Work Properly - Returns Undefined

### ISSUE THREAD

**Issue by jlmack13** [learn-co-curriculum/js-object-oriented-bind-call-apply-readme#11]
For the last example, there is a problem with the method 'favoriteBandMatches'.

In the example, it shows the favorite band (the match) being returned, but when coding along it actually returns 'undefined'.

I saw suggestions here saying it was missing an additional return statement. However, when I tried it with the suggested code it just returned the user's favorite band, regardless of whether or not there is a match to it in the array of provided bands passed into the function.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @jlmack13.

We have updated the materials including the code snippets and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
