### ISSUE TITLE
Last code example needs a callback to work

### ISSUE THREAD

**Issue by robert-laws** [learn-co-curriculum/js-object-oriented-bind-call-apply-readme#13]
I tried running the code for the last example in this lesson and it return **undefined**. In order to get it to work, I had to pass a callback to have the return value rise up to the favoriteBandMatches method in the User class.

```
class User {
  constructor(name, favoriteBand){
    this.name = name
    this.favoriteBand = favoriteBand
  }
  favoriteBandMatches(bands, callback) {
    // here this is the User instance
    bands.filter(function(band){
      // here, this is global
      if (band == this.favoriteBand) {
        return callback(this.favoriteBand);
      }
    }.bind(this))
  }
}
 
let billy = new User('billy', 'paul simon')
billy.favoriteBandMatches(['the kooks', 'paul simon', 'alvin and the chimpmunks'], function(response) {
  console.log(response)
});
```

**Comment by julianjohannesen** [comment]
I don't think you need the callback. It works if you just add a return statement before (bands.filter(...))[0]. Like:

return ( bands.filter(function(band){return band==this.favoriteBand}.bind(this) ) )[0];

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @robert-laws and @julianjohannesen.

We have updated the materials, including the code snippets in this lesson and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
