### ISSUE TITLE
Typo to be fixed. 

### ISSUE THREAD

**Issue by MiriamPeskowitz** [learn-co-curriculum/js-object-oriented-bind-call-apply-readme#14]
This edit is 1 paragraph up from the end, 3d sentence is: when the moment... 

Should be changed to: 
From the moment the method is invoked... 
of
When the method is invoked. 

Let's see why the above code works. The callback function is declared when the favoriteBandMatches method is invoked. When the moment the method is invoked, this equals the user instance receiving the method call, and we bind the callback function to that user instance. Then, from inside the filter method, the callback function is invoked - the context would be global here, except that the this is bound to User instance.

SUMMARY
We reviewed how this works for simple function calls. Then we saw how call and apply allow us to instantly execute functions while specifying the this value of the executed function. Then we learned how to use bind to make copies of functions with a new this value bound to the copy of the function.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials.
Thank you for your contribution 💙
