### ISSUE TITLE
Missing return statement

### ISSUE THREAD

**Issue by LS-C** [learn-co-curriculum/js-object-oriented-bind-call-apply-readme#8]
Hi,
Last 2 code examples for User class to bind(this) to class method favoriteBandMatches(bands)
-looks like favoriteBandMatches is missing a return statement in the before the filter block
(Line 7 -> second from the last code example / line 8-> last code example)

S

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @LS-C.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
