### ISSUE TITLE
function doesn't work. need a return value before bands.filter

### ISSUE THREAD

**Issue by rjmascolo** [learn-co-curriculum/js-object-oriented-bind-call-apply-readme#9]
`class User {
  constructor(name, favoriteBand){
    this.name = name
    this.favoriteBand = favoriteBand
  }
  favoriteBandMatches(bands){
    // here this is the User instance
    bands.filter(function(band){
      // here, this is global
      return band == this.favoriteBand
    }.bind(this))
  }
}
 
let billy = new User('billy', 'paul simon')
billy.favoriteBandMatches(['paul simon', 'the kooks'])
// 'paul simon'`

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @rjmascolo.

We have updated the materials including the code snippets in this lesson and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
